"""initial schema: ten tables

Revision ID: 4dc8f8018e70
Revises:
Create Date: 2026-08-27 15:59:52.826260

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # custom column types referenced below

# revision identifiers, used by Alembic.
revision: str = "4dc8f8018e70"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("format_config", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "file_batch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("superseded_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "accepted_at",
            app.db.types.UtcDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["file_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "content_hash", name="uq_batch_source_hash"),
    )
    with op.batch_alter_table("file_batch", schema=None) as batch_op:
        batch_op.create_index(
            "ix_batch_source_period", ["source_id", "period_start", "period_end"], unique=False
        )

    op.create_table(
        "resolution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("left_source_id", sa.Integer(), nullable=False),
        sa.Column("left_reference", sa.String(length=64), nullable=False),
        sa.Column("right_source_id", sa.Integer(), nullable=True),
        sa.Column("right_reference", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            app.db.types.UtcDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("revoked_at", app.db.types.UtcDateTime(), nullable=True),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["left_source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("resolution", schema=None) as batch_op:
        batch_op.create_index(
            "ix_resolution_left", ["left_source_id", "left_reference"], unique=False
        )
        batch_op.create_index(
            "ix_resolution_right", ["right_source_id", "right_reference"], unique=False
        )

    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("left_source_id", sa.Integer(), nullable=False),
        sa.Column("right_source_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column(
            "started_at",
            app.db.types.UtcDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", app.db.types.UtcDateTime(), nullable=True),
        sa.Column("counts", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["left_source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tolerance_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("left_source_id", sa.Integer(), nullable=False),
        sa.Column("right_source_id", sa.Integer(), nullable=False),
        sa.Column("amount_bps", app.db.types.ExactDecimal(scale=12), nullable=False),
        sa.Column("amount_abs_floor", app.db.types.ExactDecimal(scale=12), nullable=False),
        sa.Column("price_bps", app.db.types.ExactDecimal(scale=12), nullable=False),
        sa.Column("qty_bps", app.db.types.ExactDecimal(scale=12), nullable=False),
        sa.Column("time_tolerance_seconds", sa.Integer(), nullable=False),
        sa.Column("suggest_window_seconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["left_source_id"],
            ["source.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("left_source_id", "right_source_id"),
    )
    op.create_table(
        "record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("reference", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", app.db.types.UtcDateTime(), nullable=False),
        sa.Column("instrument", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", app.db.types.ExactDecimal(scale=12), nullable=False),
        sa.Column("unit_price", app.db.types.ExactDecimal(scale=12), nullable=False),
        sa.Column("gross_amount", app.db.types.ExactDecimal(scale=12), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("is_cancelled", sa.Boolean(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["file_batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("record", schema=None) as batch_op:
        batch_op.create_index("ix_record_batch", ["batch_id"], unique=False)
        batch_op.create_index("ix_record_identity", ["source_id", "reference"], unique=False)

    op.create_table(
        "rejected_row",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["file_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rejected_row", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rejected_row_batch_id"), ["batch_id"], unique=False)

    op.create_table(
        "pair",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("left_record_id", sa.Integer(), nullable=False),
        sa.Column("right_record_id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=False),
        sa.Column("resolution_id", sa.Integer(), nullable=True),
        sa.Column("max_rel_diff", app.db.types.ExactDecimal(scale=12), nullable=False),
        sa.ForeignKeyConstraint(
            ["left_record_id"],
            ["record.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolution_id"],
            ["resolution.id"],
        ),
        sa.ForeignKeyConstraint(
            ["right_record_id"],
            ["record.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "left_record_id", name="uq_pair_run_left"),
        sa.UniqueConstraint("run_id", "right_record_id", name="uq_pair_run_right"),
    )
    with op.batch_alter_table("pair", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pair_run_id"), ["run_id"], unique=False)

    op.create_table(
        "field_diff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pair_id", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=32), nullable=False),
        sa.Column("left_value", sa.String(length=64), nullable=False),
        sa.Column("right_value", sa.String(length=64), nullable=False),
        sa.Column("differs", sa.Boolean(), nullable=False),
        sa.Column("within_tolerance", sa.Boolean(), nullable=False),
        sa.Column("abs_diff", app.db.types.ExactDecimal(scale=12), nullable=True),
        sa.Column("rel_diff", app.db.types.ExactDecimal(scale=12), nullable=True),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["pair.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("field_diff", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_field_diff_pair_id"), ["pair_id"], unique=False)

    op.create_table(
        "run_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("pair_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["pair.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["record.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "record_id", name="uq_run_item"),
    )
    with op.batch_alter_table("run_item", schema=None) as batch_op:
        batch_op.create_index("ix_run_item_worklist", ["run_id", "state"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_item", schema=None) as batch_op:
        batch_op.drop_index("ix_run_item_worklist")

    op.drop_table("run_item")
    with op.batch_alter_table("field_diff", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_field_diff_pair_id"))

    op.drop_table("field_diff")
    with op.batch_alter_table("pair", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pair_run_id"))

    op.drop_table("pair")
    with op.batch_alter_table("rejected_row", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rejected_row_batch_id"))

    op.drop_table("rejected_row")
    with op.batch_alter_table("record", schema=None) as batch_op:
        batch_op.drop_index("ix_record_identity")
        batch_op.drop_index("ix_record_batch")

    op.drop_table("record")
    op.drop_table("tolerance_profile")
    op.drop_table("run")
    with op.batch_alter_table("resolution", schema=None) as batch_op:
        batch_op.drop_index("ix_resolution_right")
        batch_op.drop_index("ix_resolution_left")

    op.drop_table("resolution")
    with op.batch_alter_table("file_batch", schema=None) as batch_op:
        batch_op.drop_index("ix_batch_source_period")

    op.drop_table("file_batch")
    op.drop_table("source")
    # ### end Alembic commands ###
